### ISSUE TITLE
How to run the decompiler ?

### ISSUE THREAD

**Issue by louison85** [wfowler1/bsp-decompiler#10]
Hello, I can't launch your decompiler because I don't know which file to launch?
Thank you in advance.
![image](https://user-images.githubusercontent.com/67230657/85226214-b0df0300-b3d6-11ea-9d6b-0f2a64386b8e.png)

**Comment by EugenyP** [comment]
Need do compile, example in visual studio

**Comment by wfowler1** [comment]
The problem here is I've only supplied the source code, not a runnable program. You'd have to open the solution yourself and compile it. This isn't ideal, I should really find a way to distribute binaries...

**Comment by XEN486** [comment]
hey, you can distribute binaries with the github releases thing!

**Comment by wfowler1** [comment]
https://github.com/wfowler1/bsp-decompiler/releases/tag/v5.0.0r90
