### ISSUE TITLE
Cant get it to compile

### ISSUE THREAD

**Issue by bjansen99** [wfowler1/bsp-decompiler#14]
Hi, for some reason i cant get the program to compile. Can you provide a built version of the program? Thank you very much.

Build FAILED.

"H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\Decompiler.sln" (default target) (1) ->
"H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\Decompiler\Decompiler.csproj.metaproj" (default target) (2) ->
"H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\external\LibBSP\LibBSP\LibBSP.csproj" (default target) (3) ->
(PostBuildEvent target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5710,5): error MSB3
073: The command "cd.. [H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\external\LibBSP\LibBSP\LibBSP.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5710,5): error MSB307
3: cd.. [H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\external\LibBSP\LibBSP\LibBSP.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5710,5): error MSB307
3: cd Source\Util [H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\external\LibBSP\LibBSP\LibBSP.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5710,5): error MSB307
3: git checkout Revision.cs" exited with code 9009. [H:\Downloads\bsp-decompiler-master\bsp-decompiler-master\external\LibBSP\LibBSP\LibBSP.csproj]

**Comment by SmileyAG** [comment]
Hello, builded it via GitHub Actions with MSBuild, check this one:

[bsp-decompiler.zip](https://github.com/wfowler1/bsp-decompiler/files/7955846/bsp-decompiler.zip)

**Comment by wfowler1** [comment]
The pre build and post build steps use a git command line, I didn't realize the build would outright fail if you didn't have git.

https://github.com/wfowler1/bsp-decompiler/releases/tag/v5.0.0r90
