### ISSUE TITLE
Origin using , in floating point vector instead of .

### ISSUE THREAD

**Issue by Chrissstrahl** [wfowler1/bsp-decompiler#17]
This problem seams to be a general issue, and might cause several other issues that are listed here in other games, such as maps can not open in editor and objects being misplaced and maps not compiling.

If a entity is created from let's say a static model that has no "origin" attribute the decompiler has to create one, it does but instead of using the us standard . It uses a , for the floating point numbers of the origin.
Which is how we do it in Germany, I used a German version of vs to compile.

DECOMPILED mohaa static model data
// Entity 1236
{
"classname" "static_furniture_desk"
"model" "static/desk.tik"
"origin" "-5352,91 4966,43 -341,94"
"angles" "0 270 0"
"scale" "1"
"angle" "0"
}

The problem was discovered by konig of x-null Discord and investigated by two other people.

**Comment by 1337Smithy** [comment]
It was a cultureinfo issue. I put in a quick fix on my local copy, changing Entity.cs Origin and Angles mutators by adding ToString with format passed in:

![image](https://user-images.githubusercontent.com/64008963/182019717-ef8c2aff-ad2b-4811-82ab-9f5aabe88a61.png)

Also did the same for the scale property in StaticModelExtensions.cs ToEntity method:

![image](https://user-images.githubusercontent.com/64008963/182019907-e49d7ead-e9e0-42de-99c4-76940d82ce2d.png)

I replicated it on my machine by changing the cultureinfo to de-DE. 

I'm sure you'd want to do it in a tidier way.

**Comment by wfowler1** [comment]
Oops, not sure how I didn't see this until just now. Yeah I had to do the same thing in the map writer classes, I guess it didn't occur to me to put this in Entity as well. I didn't originally make this thing for engines that use fractional Entity origins.

**Comment by wfowler1** [comment]
Fixed in 52ec32c0a7233ddb8bd057933827179540df7307
