### ISSUE TITLE
HL BSP Decompiler error

### ISSUE THREAD

**Issue by EugenyP** [wfowler1/bsp-decompiler#2]
Exception caught in Job 1: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в LibBSP.BSP.GetReferencedObjects[T](Object o, String lumpName) в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\external\LibBSP\LibBSP\Source\Structs\BSP\BSP.cs:строка 737
   в Decompiler.BSPExtensions.GetBrushesInLeafList(BSP bsp, IEnumerable`1 leaves) в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\Decompiler\Source\Extensions\BSPExtensions.cs:строка 54
   в Decompiler.BSPExtensions.GetBrushesInModel(BSP bsp, Model model) в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\Decompiler\Source\Extensions\BSPExtensions.cs:строка 28
   в Decompiler.BSPDecompiler.ProcessEntity(Entity entity) в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\Decompiler\Source\Util\BSPDecompiler.cs:строка 71
   в Decompiler.BSPDecompiler.Decompile() в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\Decompiler\Source\Util\BSPDecompiler.cs:строка 43
   в Decompiler.Job.Run() в D:\A_CODE\bsp-decompiler-master2\bsp-decompiler-master\Decompiler\Source\Util\Job.cs:строка 166

**Comment by wfowler1** [comment]
Good catch. Though to be fair, Quake 1 and Half-Life 1 BSPs won't work with my algorithm, they're missing some of the data I depend on that every other format includes. For the moment they're not supported, though I should handle this case more gracefully than throwing an exception like this.

**Comment by wfowler1** [comment]
Not sure how long ago this was fixed but these exceptions aren't happening anymore, but maps will only have entities like #11 says. Going to close this one but 11 is still open for now.
