### ISSUE TITLE
CoD and others: "Triangle Soups" are ignored.

### ISSUE THREAD

**Issue by wfowler1** [wfowler1/bsp-decompiler#3]
The "triangle soup" portions of CoD BSP maps (and probably others) are currently ignored. These are used for things like organic terrains and other mesh-style structures where using brushes would be overly cumbersome. Must find the data format for these and process them properly.

**Comment by wfowler1** [comment]
Looks like "triangle souping" is just a method of editing brushes. Radiant seems a bit more robust when it comes to editing vertices manually than Hammer. Looks like it'll actually split a face into two or more triangles to make sure the solid is still "legal".

**Comment by EugenyP** [comment]
can the problem be solved?
