### ISSUE TITLE
MoHAA: Terrain

### ISSUE THREAD

**Issue by wfowler1** [wfowler1/bsp-decompiler#4]
Currently the MoHAA terrain is completely ignored. This is different from "triangle soups" (issue #3) and has a very different format. This data needs to be read and processed correctly.

**Comment by wfowler1** [comment]
There's probably some features not implemented, but for now this seems to work okay.

**Comment by EugenyP** [comment]
I did it, the terrain is now simply generated in patches

![image](https://github.com/user-attachments/assets/47b3ca4e-82f9-402d-8595-722c8be7f630)
